ingress:
  enabled: true
  className: "nginx"
  annotations: 
      ingress.kubernetes.io/ssl-redirect: "false"
      cert-manager.io/cluster-issuer: letsencrypt-dev
      acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: chart-app.muratnesiren.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: chart-example-tls
      hosts:
        - chart-app.muratnesiren.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits: